In [2]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a = a.reshape(2,6)
a

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
b = a.argsort(axis=0)
b

array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1]], dtype=int64)

In [5]:
c = a + a
c

array([[24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46]])

In [6]:
d = a.reshape(6,2) + np.ones((6, 2))
d

array([[13., 14.],
       [15., 16.],
       [17., 18.],
       [19., 20.],
       [21., 22.],
       [23., 24.]])

In [7]:
e = np.sqrt(a.reshape(6,2))
e

array([[3.46410162, 3.60555128],
       [3.74165739, 3.87298335],
       [4.        , 4.12310563],
       [4.24264069, 4.35889894],
       [4.47213595, 4.58257569],
       [4.69041576, 4.79583152]])

In [10]:
a1 = a.reshape(2,-1)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
b1 = a.reshape(12,-1)
b1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [12]:
c1 = a.reshape(6,-1)
c1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a1 = a.reshape(-1,3)
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
a1 = a.reshape(-1,1)
a1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [15]:
A = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
B = A.reshape (12,1)
A.ndim == B.ndim

False

In [16]:
A = np.random.randn(3, 4)
A.size

12

In [17]:
B = A.flatten()
B.size

12

In [18]:
A = np.arange(20, 0, -2)
print(A)
A.ndim, A.shape, A.size

[20 18 16 14 12 10  8  6  4  2]


(1, (10,), 10)

In [19]:
B = np.arange(20, 1, -2)
B.reshape(1,10)
print(B)
B.ndim, B.shape, B.size

[20 18 16 14 12 10  8  6  4  2]


(1, (10,), 10)

In [20]:
a = np.zeros((2, 2))

b = np.ones((3, 2))

v = np.concatenate((a, b), axis=0)
v.size

10

In [22]:
A = np.arange(12).reshape(4, 3)
A
At = A.T
At
B = A.dot(At)
print(B)
B.size
print (f'определитель матрицы равен: {np.linalg.det(B)}')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
определитель матрицы равен: 0.0


In [23]:
np.random.seed(42)

In [24]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [25]:
C = c.reshape(4, 4)
C.shape

(4, 4)

In [27]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [29]:
D_d = np.linalg.det(D)

In [30]:
np.linalg.matrix_rank(D)

4

In [31]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [32]:
D_inv = np.where (D_inv < 0, 0, 1)
D_inv
print(f'B : \n{B}\n\n C : \n{C}')
E = np.where(D_inv > 0, B, C)
print(E)

B : 
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

 C : 
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
